extends: default

# ──────────────────────────────────────────────
#  🧠 GitHub Actions–friendly YAML ruleset
# ──────────────────────────────────────────────
rules:
  # GitHub Actions: допустимо `on:` → отключаем warning "truthy"
  truthy: disable

  # разрешаем отсутствие --- в начале файлов
  document-start: disable

  # не проверяем длину строк — в CI часто длинные shell-команды
  line-length: disable

  # пробелы внутри []
  brackets:
    max-spaces-inside: 1
    min-spaces-inside: 0

  # разрешаем unicode (эмодзи, нестандартные символы в name:)
  new-lines:
    type: unix

  # допустимы 2 или 4 пробела
  indentation:
    spaces: consistent
    indent-sequences: false

  # отключаем требования к концам файлов
  trailing-spaces: disable
  new-line-at-end-of-file: disable

# ──────────────────────────────────────────────
#  🚫 Исключения
# ──────────────────────────────────────────────
ignore: |
  vendor/
  dist/
  var/
  public/
  docs/
  cache/
  tmp/
  node_modules/
  **/*.lock
  **/*.json
  **/*.xml
  **/*.md
  **/*.txt
