name: Atomicity Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  atomicity:
    name: Atomicity (core vs bridges)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run atomicity check
        run: bash sh/atomicity-check.sh
